import type { Metadata } from "next";
import { jost } from '@/app/ui/fonts';
import '@/app/ui/globals.css';
import SideBar from "@/app/ui/navigation/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) { 
  return (
   <html lang="en">
      <body className={`${jost.className} antialiased`}>
        <div className="flex min-h-screen">
          <SideBar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
